apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: nginx:alpine
      # command: ["sh", "-c", "while true; do echo Hello from Debian; sleep 10; done"]
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5
